### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kernel1024** [kernel1024/jpreader#3]
- [x] Background workers monitoring and control
 - [x] Translator cache explorer/loader
 - [x] Big files partial download
